"use client";
import Head from "next/head";
import { AuthProvider } from "none/components/Authprovider";

import { Game } from "none/components/Game";

import { GameProvider } from "none/components/GameProvider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthProvider>
        <GameProvider>
          <Game />
        </GameProvider>
      </AuthProvider>
    </>
  );
}
