"use client";
import Head from "next/head";
import { AuthProvider } from "none/components/Authprovider";
//import { GameBoard } from "../components/GameBoard";
import { Game } from "none/components/Game";

import { GameProvider } from "none/components/Provider";

// Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url(`https://fonts.googleapis.com/css2?family=Kode+Mono:wght@400..700&display=swap`,)
        </style>
      </Head>

      <AuthProvider>
        <GameProvider>
          <Game />
        </GameProvider>
      </AuthProvider>
    </>
  );
}
/*
export async function getServerSideProps() {
  // Return an empty object to disable SSR
  return {
    props: {},
  };
}
*/
