import Head from "next/head";
import { GameBoard } from "../components/GameBoard";
// Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GameBoard />
    </>
  );
}
